"""users table

Revision ID: 49274c8914ac
Revises: a8e38b128577
Create Date: 2018-06-11 19:11:28.223340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49274c8914ac'
down_revision = 'a8e38b128577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
